worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;

    upstream php-handler {
        server app:9000;
    }

    server {
        listen 80;

        root /var/www/html;
        index index.php;

        client_max_body_size 512M;

        location = /robots.txt {
            log_not_found off;
            access_log off;
        }

        location ^~ /.well-known {
            location = /.well-known/carddav {
                return 301 /remote.php/dav/;
            }

            location = /.well-known/caldav {
                return 301 /remote.php/dav/;
            }

            try_files $uri $uri/ =404;
        }

        location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/) {
            return 404;
        }

        location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
            return 404;
        }

        location ~ \.php(?:$|/) {
            rewrite ^/(?!index|remote|public|cron|core/ajax/update|status|ocs|updater|ocs-provider) /index.php$request_uri;

            fastcgi_split_path_info ^(.+?\.php)(/.*)$;

            set $path_info $fastcgi_path_info;

            try_files $fastcgi_script_name =404;

            include fastcgi_params;

            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $path_info;
            fastcgi_param HTTP_PROXY "";

            fastcgi_param front_controller_active true;

            fastcgi_pass php-handler;

            fastcgi_intercept_errors on;
        }

        location / {
            try_files $uri $uri/ /index.php$request_uri;
        }
    }
}